version: '3.3'
services:
  postgres-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee-shop
    volumes:
      - ./coffee-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    image: duc2495/coffee-shop
    ports:
      - 80:8080
    volumes:
      - ./coffee-shop/images/products/:/root/coffee-shop/images/products
    depends_on:
      - postgres-db
